### ISSUE TITLE
Why does types have 'material-***' 

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly-template-material#2]
I believe that a project would either use material, or use bootstrap, they won't have both material and bootstrap in the project. So the usage of 'material-input', 'material-checkbox' does not make sense, I would rather prefer 'input', 'checkbox' etc to be my type names.

**Comment by divyakumarjain** [comment]
What you are saying make sense. I also quickly looked formly for angularjs and seem like across different template no prefix are used. Will update the repo with a PR.
