### ISSUE TITLE
Integration with Angular 2

### ISSUE THREAD

**Issue by psegarel** [formly-js/ng2-formly-template-material#4]
Any chance for some docs on how to integrate ng-formly-template-material with Angular 2.
I couldn't find any resources about this subject!

Thanks! 👍

**Comment by yzargar** [comment]
@psegarel  I guess there is FormlyMaterialModule that you need to import in your app. Please check with the demo folder on github repo.

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ng-formly#2-choose-and-install-your-ui-pre-defined-typestemplates-package
